### ISSUE TITLE
Lale default install issues with Python 3.8

### ISSUE THREAD

**Issue by mfeffer** [IBM/lale#688]
OS: Mac OS 11.3.1 (Big Sur)
Python version: 3.8

Running `pip install lale[full]` with Python 3.8 causes issues at runtime. Specifically, after installing dependencies beyond pip like `swig`, running cells (or at least the first cell) in the `demo_aif30` notebook from the examples produced blocking errors.

The first was `module 'black' has no attribute 'Mode'`. I caused this to go away by running `pip install --upgrade black` to install the latest version of the package (v21), but based on [this commit](https://github.com/IBM/lale/commit/c8ec39b5a9118de89db46c8d2dffb62fb57d1d71), that may not actually be the correct fix.

Regardless, I soon ran into another issue related to interactions between `numpy` and `tensorflow`. After making the change to `black`, re-running the cell produced `module compiled against API version 0xe but this version of numpy is 0xd`. Installing the latest version of `numpy` (v1.20) via pip resulted in a warning that said `tensorflow` at version 2.5.0 (the one installed by default for my version of Python 3.8) would not be compatible (and would only work with versions close to 1.19.2). Downgrading `numpy` back to an earlier version would result in the `0xe` error again, so it was impossible to proceed from here.

A workaround is to just use Python 3.7 (I've gotten everything to work virtually out of the box with this version), but I figured the installation issues and dependency incompatibility should be noted somewhere (especially as docs mention that any version beyond 3.6 should work).
